baseurl: "/"
permalink: pretty
title: "Tyler A. Young’s Blog"
collections_dir: collections
markdown: kramdown
highlighter: rouge
domain: https://tylerayoung.com

sass:
  indentWidth: 4
  style: compact
  precision: 10

google_analytics_id: false # replace with "UA-XXXX"

logo:
  logo_desktop_image: assets/images/logo/logo.svg
  logo_desktop_text: "Tyler A. <strong>Young</strong>"
  logo_mobile_image: assets/images/logo/logo.svg
  logo_mobile_text: "Tyler A. <strong>Young</strong>"
  logo_desktop_height: "36px"
  logo_desktop_width: "36px"
  logo_mobile_height: "36px"
  logo_mobile_width: "36px"

seo:
  meta_twitter_site: "@TylerAYoung"
  meta_twitter_creator: "@TylerAYoung"
  meta_og_image: "/assets/images/oakland/2022-04-07-15.23.44-rockies-landscape.jpg"

plugins:
  - jekyll-environment-variables
  - jekyll-postcss
  - jekyll-paginate
  - jekyll-image-size

paginate: 20
paginate_path: /:num/

collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: "images"
    values:
      image: true
  - scope:
      path: "categories"
    values:
      layout: category
      permalink: /category/:basename/

imagesurl: "/assets/images/"
# Some day I might generate separate thumbnails in a mirrored structure
thumbsurl: "/assets/thumbs/"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - package.json
  - package-lock.json
  - vendor
  - LICENSE.md
  - LICENSE
  - README.md
  - .vscode
  - .gitignore
  - .liquidrc
  - postcss.config.js
  - tailwind.config.js
  - netlify.toml
